### ISSUE TITLE
Would you ever consider selling these pre-built?

### ISSUE THREAD

**Issue by ThatOneCalculator** [loopj/short-stack#1]
Came across this on HN, I've had an interest in minified GameCubes and Wiis and this looks awesome! Maybe not right now, but in the future would you ever consider making and selling these?

**Comment by AidenSorabji** [comment]
I'd buy one ngl if it was a prebuilt, if its also => $100 then I'd spend my money instantly

**Comment by loopj** [comment]
Thanks for the kind words! This is purely a "for fun" project, and I have no plans on selling these, but since it is open source there's nothing stopping someone else from making commissions!

**Comment by ThatOneCalculator** [comment]
Ah, gotcha! Are there any makers in the space that you could recommend?

**Comment by loopj** [comment]
[CrazyGadget](https://twitter.com/crazygadgetmods) sometimes takes commissions! He and Wesk are the creators of the [GC Nano](https://bitbuilt.net/forums/index.php?threads/gc-nano-the-worlds-smallest-gamecube.5697/) which was a huge inspiration for this project.
